# GitHub Pages Configuration for Google Docs MCP Server
title: LLM2Docs - Google Docs MCP Server
description: A powerful Model Context Protocol server for comprehensive Google Docs automation and technical documentation
author: NoManNayeem
url: https://nomanayeem.github.io/google-docs-mcp-server
baseurl: /google-docs-mcp-server

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Navigation
navigation:
  - title: Features
    url: /google-docs-mcp-server/#features
  - title: Quick Start
    url: /google-docs-mcp-server/#quick-start
  - title: Documentation
    url: /google-docs-mcp-server/#documentation
  - title: Examples
    url: /google-docs-mcp-server/#examples
  - title: GitHub
    url: https://github.com/NoManNayeem/google-docs-mcp-server

# Social links
social:
  - name: GitHub
    url: https://github.com/NoManNayeem/google-docs-mcp-server
  - name: Issues
    url: https://github.com/NoManNayeem/google-docs-mcp-server/issues
  - name: Discussions
    url: https://github.com/NoManNayeem/google-docs-mcp-server/discussions

# SEO
seo:
  title: LLM2Docs - Google Docs MCP Server
  description: A powerful Model Context Protocol server for comprehensive Google Docs automation and technical documentation with Claude AI
  keywords: mcp, google-docs, automation, technical-documentation, claude, ai, model-context-protocol
  author: NoManNayeem
  image: /google-docs-mcp-server/assets/og-image.png

# Analytics (if needed)
# google_analytics: GA_MEASUREMENT_ID

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"
